import Meal from "../../mealsModel";

export const MOST_POPULAR_BREAKFAST = [
  new Meal(
    "1",
    "Pancakes with Maple Syrup",
    "https://media.istockphoto.com/id/109726917/photo/whole-wheat-pancakes-with-maple-syrup.webp?a=1&b=1&s=612x612&w=0&k=20&c=mtbFhZpHWg5sgYkdS6JGGppBiFn9MrdQBOXxwL8fGt0=",
    20,
    2,
    ["pancake-mix", "maple-syrup", "butter"],
    ["200g", "100ml", "1 tbsp"],
    4,
    ["pan", "spatula", "mixing-bowl"],
    [
      "In a large mixing bowl, combine the pancake mix with water (follow the package instructions for the correct ratio) and whisk until the batter is smooth.",
      "Heat a non-stick pan over medium heat and lightly grease with butter.",
      "Pour a ladleful of the batter onto the pan and cook until bubbles form on the surface (about 5 minutes). Flip and cook the other side for another 2 minutes.",
      "Serve warm with maple syrup drizzled on top.",
    ],
    false,
    "Breakfast",
    "Fluffy pancakes with rich maple syrup.",
    ["Sweet", "Quick", "Comfort Food"],
    { calories: 350, protein: "8g", carbs: "60g", fat: "10g" }, // Nutrition Facts
    ["Pancake mix", "Maple syrup", "Butter"], // Grocery List
    ["2 minutes", "2 minutes", "7 minutes", "1 minute"] // Duration Array
  ),
  new Meal(
    "2",
    "Chicken and Waffles",
    "https://media.istockphoto.com/id/1325150602/photo/waffles-with-fried-chicken.webp?a=1&b=1&s=612x612&w=0&k=20&c=9VAOtT-wdRuwOowO6fxXzkfMjh2skjoBfZ4ZTSQzykw=",
    30,
    2,
    ["chicken", "waffle-batter", "maple-syrup"],
    ["200g", "150g", "50ml"],
    4,
    ["waffle-maker", "frying-pan"],
    [
      "Preheat your waffle maker. Prepare the waffle batter according to the package instructions and set aside.",
      "Heat a frying pan with enough oil to shallow-fry the chicken. Season the chicken with salt, pepper, and optional spices, then fry until golden brown and cooked through (about 8 minutes per side).",
      "Pour the waffle batter into the waffle maker and cook until golden and crisp.",
      "Serve the fried chicken on top of the waffles and drizzle with maple syrup.",
    ],
    true,
    "Breakfast",
    "Crispy fried chicken served on golden waffles.",
    ["Sweet", "Savory", "American"],
    { calories: 700, protein: "40g", carbs: "75g", fat: "30g" },
    ["Chicken", "Waffle batter", "Maple syrup", "Oil"],
    ["5 minutes", "16 minutes", "5 minutes", "1 minute"]
  ),
  new Meal(
    "3",
    "Vegetarian Omelette",
    "https://media.istockphoto.com/id/1430574902/photo/omelet-with-fried-mushrooms-and-fresh-herbs-in-a-plate-on-a-concrete-background-delicious.webp?a=1&b=1&s=612x612&w=0&k=20&c=RQVT2hbr9ailT3TQtOAC4DWQiZP6E2HUxjrCkmywyqk=",
    15,
    1,
    ["eggs", "mushrooms", "cheese", "spinach"],
    ["3", "50g", "30g", "20g"],
    4,
    ["pan", "whisk", "knife"],
    [
      "Crack the eggs into a bowl, add a pinch of salt and pepper, and whisk until fully mixed.",
      "Slice the mushrooms and sauté them in a non-stick pan over medium heat until tender (about 5 minutes).",
      "Pour the whisked eggs over the mushrooms and sprinkle spinach and grated cheese on top.",
      "Cook until the omelette is set, then fold in half and serve immediately.",
    ],
    false,
    "Breakfast",
    "Healthy omelette loaded with fresh vegetables.",
    ["Vegetarian", "Quick", "Protein"],
    { calories: 250, protein: "20g", carbs: "5g", fat: "18g" },
    ["Eggs", "Mushrooms", "Cheese", "Spinach"],
    ["2 minutes", "5 minutes", "1 minute", "3 minutes"]
  ),
  new Meal(
    "4",
    "Avocado Toast with Poached Egg",
    "https://media.istockphoto.com/id/2163788896/photo/poached-eggs-on-toasted-bread-eggs-benedict-with-spinach-delicious-fresh-benedict-eggs.webp?a=1&b=1&s=612x612&w=0&k=20&c=_f1eeez4FvrDKFRPe3G5Gce4FyWKgdvWiQSUJ968SpM=",
    10,
    1,
    ["bread", "avocado", "egg", "lemon"],
    ["2 slices", "1", "1", "1/2"],
    4,
    ["toaster", "pot", "knife"],
    [
      "Toast the bread slices in a toaster until golden brown.",
      "Slice the avocado in half, remove the pit, and mash the flesh in a bowl with a squeeze of lemon juice.",
      "Bring a pot of water to a gentle simmer, crack an egg into a small cup, and carefully slide it into the water. Cook for 3-4 minutes until the whites are set.",
      "Spread the mashed avocado onto the toasted bread, top with the poached egg, and season with salt and pepper to taste (about 5 minutes total preparation time).",
    ],
    false,
    "Breakfast",
    "Creamy avocado on toast topped with a perfectly poached egg.",
    ["Healthy", "Quick", "Trendy"],
    { calories: 300, protein: "12g", carbs: "30g", fat: "18g" },
    ["Bread", "Avocado", "Egg", "Lemon"],
    ["2 minutes", "2 minutes", "3 minutes", "1 minute"]
  ),
  new Meal(
    "5",
    "Egg and Cheese Bagel Sandwich",
    "https://media.istockphoto.com/id/2178718682/photo/bagel-sandwich-withmacon-and-fried-egg.webp?a=1&b=1&s=612x612&w=0&k=20&c=qIBGA6Q_7cN3Rl_nH4YgrWdbkdwemKoCcY6v6RTkQfE=",
    15,
    1,
    ["bagel", "egg", "cheese"],
    ["1", "1", "1 slice"],
    3,
    ["pan", "toaster"],
    [
      "Toast the bagel slices in a toaster until golden brown (about 5 minutes).",
      "Cook an egg in a frying pan to your desired consistency (fried or scrambled).",
      "Assemble the sandwich by layering the egg and cheese on the toasted bagel.",
      "Serve warm.",
    ],
    false,
    "Breakfast",
    "Hearty bagel sandwich with egg and melted cheese.",
    ["Quick", "Savory", "Comfort Food"],
    { calories: 400, protein: "20g", carbs: "45g", fat: "15g" },
    ["Bagel", "Egg", "Cheese"],
    ["5 minutes", "3 minutes", "1 minute", "1 minute"]
  ),
  new Meal(
    "6",
    "Smoked Salmon on Rye Bread",
    "https://media.istockphoto.com/id/1222564135/photo/bruschetta-with-salmon-curd-cheese-and-cucumber-on-toast-in-high-key-style-on-white-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=sSDWoADrZ_TXXSYAuPg6ZxzIcnFCW20BQydigriEAF8=",
    10,
    1,
    ["rye-bread", "smoked-salmon", "cream-cheese"],
    ["2 slices", "50g", "20g"],
    3,
    ["knife", "toaster"],
    [
      "Toast the rye bread slices until golden brown (about 5 minutes).",
      "Spread cream cheese evenly on each slice of bread.",
      "Top with smoked salmon and serve immediately.",
    ],
    true,
    "Breakfast",
    "Elegant smoked salmon served on rye bread.",
    ["Savory", "Quick", "Protein"],
    { calories: 320, protein: "22g", carbs: "35g", fat: "12g" },
    ["Rye bread", "Smoked salmon", "Cream cheese"],
    ["5 minutes", "1 minute", "1 minute"]
  ),
];