import Meal from "../../mealsModel";

export const MOST_POPULAR_DINNER = [
  new Meal(
    "1",
    "Grilled Lemon Herb Chicken with Vegetables",
    "https://media.istockphoto.com/id/157336239/photo/grilled-chicken-breast.webp?a=1&b=1&s=612x612&w=0&k=20&c=ITrCRJqnmfU2Ks6PtLluBHl2hHt4MxN6OLfLylVs5AA=",
    40,
    4,
    ["chicken-breast", "lemon", "herbs", "vegetables"],
    ["500g", "1", "2 tbsp", "300g"],
    3,
    ["grill-pan", "knife", "cutting-board"],
    [
      "Pat the chicken breasts dry with paper towels.",
      "In a bowl, mix lemon juice, herbs, salt, and pepper to create the marinade.",
      "Coat the chicken with the marinade and let it sit for at least 20 minutes.",
      "Preheat a grill pan over medium heat for 5 minutes.",
      "Place the chicken on the grill and cook for 6-8 minutes per side.",
      "While the chicken cooks, wash and chop the vegetables into bite-sized pieces (about 5 minutes).",
      "Lightly coat the vegetables with olive oil and season with salt and pepper.",
      "Grill the vegetables for 3-5 minutes until slightly charred but still crisp.",
      "Remove the chicken from the grill and let it rest for 5 minutes before slicing.",
      "Serve hot with the grilled vegetables on the side.",
    ],
    false,
    "Dinner",
    "Juicy chicken with fresh herbs and veggies.",
    ["Healthy", "Grilled", "Low-carb"],
    {
      calories: 320,
      protein: 38,
      carbs: 12,
      fat: 14,
      fiber: 4,
      sugar: 3,
    },
    [
      "Chicken breast",
      "Fresh lemon",
      "Mixed herbs (rosemary, thyme, oregano)",
      "Mixed vegetables (zucchini, bell peppers, carrots)",
      "Olive oil",
      "Salt",
      "Black pepper",
    ]
  ),
  new Meal(
    "2",
    "Spaghetti Bolognese",
    "https://media.istockphoto.com/id/1471612291/photo/spaghetti-with-bolognese-sauce-on-wooden-table.webp?a=1&b=1&s=612x612&w=0&k=20&c=ZdFmb-TxaiOSk_DaNJo22xbeBI6e9BfXdZR68oUG44Y=",
    50,
    4,
    ["spaghetti", "ground-beef", "tomato-sauce", "onion", "garlic"],
    ["400g", "500g", "200ml", "1", "2 cloves"],
    4,
    ["pot", "pan", "strainer"],
    [
      "Bring a large pot of salted water to a rolling boil.",
      "Add the spaghetti and cook according to package instructions (about 8-10 minutes).",
      "Drain the pasta and toss with a little olive oil to prevent sticking.",
      "Finely chop the onion and mince the garlic.",
      "In a large pan, heat oil and sauté the onion and garlic until soft and fragrant.",
      "Add the ground beef, breaking it apart as it cooks, until browned.",
      "Drain excess fat from the pan if needed.",
      "Pour in the tomato sauce and stir well.",
      "Let the sauce simmer on low heat for 15 minutes, stirring occasionally.",
      "Season with salt, pepper, and Italian herbs to taste.",
      "Combine the sauce with the spaghetti, toss well, and serve with grated Parmesan cheese.",
    ],
    false,
    "Dinner",
    "Classic Italian pasta dish with rich meat sauce.",
    ["Italian", "Comfort Food", "Pasta"],
    {
      calories: 290,
      protein: "32g",
      fat: "14g",
      carbs: "10g",
      fiber: "1g",
      sugar: "1g",
    },
    [
      "Spaghetti pasta",
      "Ground beef",
      "Tomato sauce",
      "Yellow onion",
      "Garlic cloves",
      "Olive oil",
      "Italian herbs",
      "Salt",
      "Black pepper",
      "Parmesan cheese",
    ]
  ),
  new Meal(
    "3",
    "Beef Stroganoff",
    "https://media.istockphoto.com/id/487537715/photo/beef-stroganoff.webp?a=1&b=1&s=612x612&w=0&k=20&c=FiNJWl9FQaN3aCokz7zCWcB1yLzgGRf_Y9fwZbzcx9M=",
    45,
    4,
    ["beef", "mushrooms", "sour-cream", "onion", "butter"],
    ["500g", "200g", "150ml", "1", "2 tbsp"],
    4,
    ["pan", "knife", "spoon"],
    [
      "Slice the beef into thin strips and season with salt and pepper.",
      "Heat butter in a large pan over medium-high heat.",
      "Sear the beef until browned on all sides (about 5-6 minutes). Remove and set aside.",
      "Slice the mushrooms and finely chop the onion.",
      "In the same pan, add more butter and sauté the onions until translucent.",
      "Add the mushrooms and cook until softened.",
      "Return the beef to the pan and stir everything together.",
      "Lower the heat and stir in the sour cream until well combined.",
      "Let the mixture simmer for 5-7 minutes, stirring occasionally.",
      "Adjust seasoning if needed and serve hot over cooked rice or pasta.",
    ],
    true,
    "Dinner",
    "Creamy beef dish with mushrooms and sour cream.",
    ["Russian", "Creamy", "Comfort Food"],
  ),
  new Meal(
    "4",
    "Vegetarian Stir-Fried Noodles",
    "https://media.istockphoto.com/id/1156141303/photo/asian-vegetarian-food-udon-noodles-with-baby-bok-choy-shiitake-mushrooms-sesame-and-pepper.webp?a=1&b=1&s=612x612&w=0&k=20&c=1U4kysvA3uS3N0oON9kxxQKIEN8_TTQ1v9KS4cnCZL8=",
    25,
    3,
    ["noodles", "bok-choy", "mushrooms", "soy-sauce", "sesame-oil"],
    ["300g", "2 cups", "1 cup", "2 tbsp", "1 tbsp"],
    3,
    ["wok", "spatula", "knife"],
    [
      "Boil a pot of water and cook the noodles according to package instructions (about 5-7 minutes).",
      "Drain and rinse the noodles under cold water to prevent sticking.",
      "Chop the bok choy and slice the mushrooms.",
      "Heat sesame oil in a wok over medium-high heat.",
      "Add the mushrooms and bok choy, stirring frequently for 3-5 minutes.",
      "Pour in the soy sauce and mix well.",
      "Add the cooked noodles to the wok and toss everything together.",
      "Stir-fry for another 2-3 minutes until the noodles are well coated.",
      "Taste and adjust seasoning if needed.",
      "Serve hot with sesame seeds or green onions as garnish.",
    ],
    false,
    "Dinner",
    "Quick stir-fried noodles with fresh vegetables.",
    ["Vegetarian", "Asian", "Quick"],
  )
];